---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Human-Robot Interaction for Cashier Robot"
keywords:    "Baxter, Python, Robotics, Human-Robot Interaction"
description: "Home page of final year project 'Human-Robot Interaction for Cashier Robot'"
source_link: "https://github.com/papallas/baxter_cashier"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
